# version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      TMDB_API_URL: ${TMDB_API_URL}
      TMDB_API_KEY: ${TMDB_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      # REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      NODE_ENV: ${NODE_ENV}
    # depends_on:
    #   - mongodb
    #   - redis

  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   # volumes:
  #   #   - redis_data:/data
  #   # command: redis-server --appendonly yes

  # mongodb:
  #   image: mongo
  #   ports:
  #     - "27019:27017"
  #   # environment:
  #   #   - MONGO_INITDB_ROOT_USERNAME=admin
  #   #   - MONGO_INITDB_ROOT_PASSWORD=password
  #   # volumes:
  #   #   - mongodb_data:/data/db
  #   # restart: unless-stopped

# volumes:
#   redis_data:
#   mongodb_data: